name: audio-replacer
base: core22
version: '5.0.0'
summary: Streamline video game voice-over dubbing
description: |
  This app aims to streamline the production of video game mods that dub over voice-over content (i.e. voice-over translation mods)
type: app
grade: stable
confinement: strict
source-code:
  - https://github.com/lemons-studios/audio-replacer

contact:
  - andrewpinter23@gmail.com

issues:
  - https://github.com/lemons-studios/audio-replacer/issues

compression: lzo

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.1

apps:
  audio-replacer:
    command: usr/bin/audio-replacer
    desktop: usr/share/applications/audio-replacer.desktop
    extensions: [gnome]
    plugs:
      - network
      - audio-playback
      - audio-record
slots:
  single-instance:
    interface: dbus
    bus: session
    name: org.lemon-studios_audio-replacer.SingleInstance

plugs:
  single-instance-plug:
    interface: dbus
    bus: session
    name: org.lemon-studios_audio-replacer.SingleInstance

parts:
  build-app:
    plugin: dump
    source: .
    override-build: |
      set -e
      dpkg -x src-tauri/target/release/bundle/deb/*.deb $SNAPCRAFT_PART_INSTALL/
#      sed -i -e "s|Icon=audio-replacer|Icon=/usr/share/icons/hicolor/32x32/apps/audio-replacer.png|g" $SNAPCRAFT_PART_INSTALL/usr/share/applications/audio-replacer.desktop
