export const editorTheme = {
	base: "vs-dark",
	inherit: false,
	rules: [
		{ token: "invalid", foreground: "#ed8796" },
		{ token: "emphasis", fontStyle: "italic" },
		{ token: "strong", fontStyle: "bold" },

		{ token: "variable", foreground: "#cad3f5" },
		{ token: "variable.predefined", foreground: "#8aadf4" },
		{ token: "variable.parameter", foreground: "#ee99a0" },
		{ token: "constant", foreground: "#ed8796" },
		{ token: "comment", foreground: "#6e738d", fontStyle: "italic" },
		{ token: "number", foreground: "#f5a97f" },
		{ token: "number.hex", foreground: "#8bd5ca" },
		{ token: "regexp", foreground: "#a6da95" },
		{ token: "annotation", foreground: "#f5a97f" },
		{ token: "type", foreground: "#eed49f" },

		{ token: "delimiter", foreground: "#cad3f5" },
		{ token: "delimiter.html", foreground: "#cad3f5" },

		{ token: "tag", foreground: "#8aadf4" },
		{ token: "meta.tag", foreground: "#8aadf4" },
		{ token: "metatag", foreground: "#8aadf4" },
		{ token: "metatag.content.html", foreground: "#cad3f5" },
		{ token: "metatag.html", foreground: "#8aadf4" },

		{ token: "key", foreground: "#8aadf4" },
		{ token: "string.key.json", foreground: "#8aadf4" },
		{ token: "string.value.json", foreground: "#f5a97f" },

		{ token: "string", foreground: "#a6da95" },

		{ token: "keyword", foreground: "#c6a0f6" },
	],
	colors: {
		focusBorder: "#93c5fd",
		foreground: "#cad3f5",
		disabledForeground: "#a5adcb",
		"widget.shadow": "#11182780",
		"selection.background": "#93c5fd66",
		descriptionForeground: "#cad3f5",
		errorForeground: "#ed8796",
		"icon.foreground": "#93c5fd",
		"sash.hoverBorder": "#93c5fd",
		"window.activeBorder": "#00000000",
		"window.inactiveBorder": "#00000000",
		"textBlockQuote.background": "#111827",
		"textBlockQuote.border": "#181926",
		"textCodeBlock.background": "#0b0908",
		"textLink.activeForeground": "#91d7e3",
		"textLink.foreground": "#8aadf4",
		"textPreformat.foreground": "#cad3f5",
		"textSeparator.foreground": "#93c5fd",
		"badge.background": "#4b5563",
		"badge.foreground": "#cad3f5",
		"breadcrumb.activeSelectionForeground": "#93c5fd",
		"breadcrumb.background": "#24273a",
		"breadcrumb.focusForeground": "#93c5fd",
		"breadcrumb.foreground": "#cad3f5cc",
		"breadcrumbPicker.background": "#0b0908",
		"button.background": "#93c5fd",
		"button.foreground": "#181926",
		"button.border": "#00000000",
		"button.separator": "#00000000",
		"button.hoverBackground": "#dac1f9",
		"button.secondaryForeground": "#cad3f5",
		"button.secondaryBackground": "#5b6078",
		"button.secondaryHoverBackground": "#6a708c",
		"diffEditor.border": "#5b6078",
		"diffEditor.insertedTextBackground": "#a6da951a",
		"diffEditor.removedTextBackground": "#ed87961a",
		"diffEditor.insertedLineBackground": "#a6da9526",
		"diffEditor.removedLineBackground": "#ed879626",
		"diffEditor.diagonalFill": "#5b607899",
		"diffEditorOverview.insertedForeground": "#a6da95cc",
		"diffEditorOverview.removedForeground": "#ed8796cc",
		"editor.background": "#0b0908",
		"editor.findMatchBackground": "#604456",
		"editor.findMatchBorder": "#ed879633",
		"editor.findMatchHighlightBackground": "#455c6d",
		"editor.findMatchHighlightBorder": "#91d7e333",
		"editor.findRangeHighlightBackground": "#455c6d",
		"editor.findRangeHighlightBorder": "#91d7e333",
		"editor.foldBackground": "#91d7e340",
		"editor.foreground": "#cad3f5",
		"editor.hoverHighlightBackground": "#91d7e340",
		"editor.lineHighlightBackground": "#cad3f512",
		"editor.lineHighlightBorder": "#00000000",
		"editor.rangeHighlightBackground": "#91d7e340",
		"editor.rangeHighlightBorder": "#00000000",
		"editor.selectionBackground": "#9ca3af40",
		"editor.selectionHighlightBackground": "#9ca3af33",
		"editor.selectionHighlightBorder": "#939ab733",
		"editor.wordHighlightBackground": "#9ca3af33",
		"editorBracketMatch.background": "#9ca3af1a",
		"editorBracketMatch.border": "#9ca3af",
		"editorCodeLens.foreground": "#9ca3af",
		"editorCursor.background": "#24273a",
		"editorCursor.foreground": "#f4dbd6",
		"editorGroup.border": "#5b6078",
		"editorGroup.dropBackground": "#93c5fd33",
		"editorGroup.emptyBackground": "#24273a",
		"editorGroupHeader.tabsBackground": "#181926",
		"editorGutter.addedBackground": "#a6da95",
		"editorGutter.background": "#0b0908",
		"editorGutter.commentRangeForeground": "#363a4f",
		"editorGutter.commentGlyphForeground": "#93c5fd",
		"editorGutter.deletedBackground": "#ed8796",
		"editorGutter.foldingControlForeground": "#939ab7",
		"editorGutter.modifiedBackground": "#eed49f",
		"editorHoverWidget.background": "#111827",
		"editorHoverWidget.border": "#5b6078",
		"editorHoverWidget.foreground": "#cad3f5",
		"editorIndentGuide.activeBackground": "#5b6078",
		"editorIndentGuide.background": "#4b5563",
		"editorInlayHint.foreground": "#5b6078",
		"editorInlayHint.background": "#111827bf",
		"editorInlayHint.typeForeground": "#b8c0e0",
		"editorInlayHint.typeBackground": "#0b0908",
		"editorInlayHint.parameterForeground": "#a5adcb",
		"editorInlayHint.parameterBackground": "#0b0908",
		"editorLineNumber.activeForeground": "#93c5fd",
		"editorLineNumber.foreground": "#9ca3af",
		"editorLink.activeForeground": "#93c5fd",
		"editorMarkerNavigation.background": "#111827",
		"editorMarkerNavigationError.background": "#ed8796",
		"editorMarkerNavigationInfo.background": "#8aadf4",
		"editorMarkerNavigationWarning.background": "#f5a97f",
		"editorOverviewRuler.background": "#131313",
		"editorOverviewRuler.border": "#cad3f512",
		"editorOverviewRuler.modifiedForeground": "#eed49f",
		"editorRuler.foreground": "#5b6078",
		"editor.stackFrameHighlightBackground": "#eed49f26",
		"editor.focusedStackFrameHighlightBackground": "#a6da9526",
		"editorStickyScrollHover.background": "#363a4f",
		"editorSuggestWidget.background": "#111827",
		"editorSuggestWidget.border": "#5b6078",
		"editorSuggestWidget.foreground": "#cad3f5",
		"editorSuggestWidget.highlightForeground": "#93c5fd",
		"editorSuggestWidget.selectedBackground": "#374151",
		"editorWhitespace.foreground": "#9ca3af66",
		"editorWidget.background": "#111827",
		"editorWidget.foreground": "#cad3f5",
		"editorWidget.resizeBorder": "#5b6078",
		"editorLightBulb.foreground": "#eed49f",
		"editorError.foreground": "#ed8796",
		"editorError.border": "#00000000",
		"editorError.background": "#00000000",
		"editorWarning.foreground": "#f5a97f",
		"editorWarning.border": "#00000000",
		"editorWarning.background": "#00000000",
		"editorInfo.foreground": "#8aadf4",
		"editorInfo.border": "#00000000",
		"editorInfo.background": "#00000000",
		"problemsErrorIcon.foreground": "#ed8796",
		"problemsInfoIcon.foreground": "#8aadf4",
		"problemsWarningIcon.foreground": "#f5a97f",
		"input.background": "#374151",
		"input.border": "#00000000",
		"input.foreground": "#cad3f5",
		"input.placeholderForeground": "#cad3f573",
		"inputOption.activeBackground": "#5b6078",
		"inputOption.activeBorder": "#93c5fd",
		"inputOption.activeForeground": "#cad3f5",
		"inputValidation.errorBackground": "#ed8796",
		"inputValidation.errorBorder": "#18192633",
		"inputValidation.errorForeground": "#181926",
		"inputValidation.infoBackground": "#8aadf4",
		"inputValidation.infoBorder": "#18192633",
		"inputValidation.infoForeground": "#181926",
		"inputValidation.warningBackground": "#f5a97f",
		"inputValidation.warningBorder": "#18192633",
		"inputValidation.warningForeground": "#181926",
		"list.activeSelectionBackground": "#374151",
		"list.activeSelectionForeground": "#cad3f5",
		"list.dropBackground": "#93c5fd33",
		"list.focusBackground": "#374151",
		"list.focusForeground": "#cad3f5",
		"list.focusOutline": "#00000000",
		"list.highlightForeground": "#93c5fd",
		"list.hoverBackground": "#37415180",
		"list.hoverForeground": "#cad3f5",
		"list.inactiveSelectionBackground": "#374151",
		"list.inactiveSelectionForeground": "#cad3f5",
		"list.warningForeground": "#f5a97f",
		"listFilterWidget.background": "#494d64",
		"listFilterWidget.noMatchesOutline": "#ed8796",
		"listFilterWidget.outline": "#00000000",
		"tree.indentGuidesStroke": "#939ab7",
		"tree.inactiveIndentGuidesStroke": "#494d64",
		"menu.background": "#24273a",
		"menu.border": "#24273a80",
		"menu.foreground": "#cad3f5",
		"menu.selectionBackground": "#5b6078",
		"menu.selectionBorder": "#00000000",
		"menu.selectionForeground": "#cad3f5",
		"menu.separatorBackground": "#5b6078",
		"menubar.selectionBackground": "#494d64",
		"menubar.selectionForeground": "#cad3f5",
		"merge.commonContentBackground": "#494d64",
		"merge.commonHeaderBackground": "#5b6078",
		"merge.currentContentBackground": "#a6da9533",
		"merge.currentHeaderBackground": "#a6da9566",
		"merge.incomingContentBackground": "#8aadf433",
		"merge.incomingHeaderBackground": "#8aadf466",
		"minimap.background": "#1e203080",
		"minimap.findMatchHighlight": "#91d7e34d",
		"minimap.selectionHighlight": "#5b6078bf",
		"minimap.selectionOccurrenceHighlight": "#5b6078bf",
		"minimap.warningHighlight": "#f5a97fbf",
		"minimap.errorHighlight": "#ed8796bf",
		"minimapSlider.background": "#d1d5db33",
		"minimapSlider.hoverBackground": "#d1d5db66",
		"minimapSlider.activeBackground": "#d1d5db99",
		"minimapGutter.addedBackground": "#a6da95bf",
		"minimapGutter.deletedBackground": "#ed8796bf",
		"minimapGutter.modifiedBackground": "#eed49fbf",
		"notificationCenter.border": "#93c5fd",
		"notificationCenterHeader.foreground": "#cad3f5",
		"notificationCenterHeader.background": "#1e2030",
		"notificationToast.border": "#93c5fd",
		"notifications.foreground": "#cad3f5",
		"notifications.background": "#1e2030",
		"notifications.border": "#93c5fd",
		"notificationLink.foreground": "#8aadf4",
		"notificationsErrorIcon.foreground": "#ed8796",
		"notificationsWarningIcon.foreground": "#f5a97f",
		"notificationsInfoIcon.foreground": "#8aadf4",
		"panel.background": "#24273a",
		"panel.border": "#5b6078",
		"panelSection.border": "#5b6078",
		"panelSection.dropBackground": "#93c5fd33",
		"panelTitle.activeBorder": "#93c5fd",
		"panelTitle.activeForeground": "#cad3f5",
		"panelTitle.inactiveForeground": "#a5adcb",
		"peekView.border": "#93c5fd",
		"peekViewEditor.background": "#111827",
		"peekViewEditorGutter.background": "#111827",
		"peekViewEditor.matchHighlightBackground": "#91d7e34d",
		"peekViewEditor.matchHighlightBorder": "#00000000",
		"peekViewResult.background": "#111827",
		"peekViewResult.fileForeground": "#cad3f5",
		"peekViewResult.lineForeground": "#cad3f5",
		"peekViewResult.matchHighlightBackground": "#91d7e34d",
		"peekViewResult.selectionBackground": "#374151",
		"peekViewResult.selectionForeground": "#cad3f5",
		"peekViewTitle.background": "#0b0908",
		"peekViewTitleDescription.foreground": "#b8c0e0b3",
		"peekViewTitleLabel.foreground": "#cad3f5",
		"pickerGroup.border": "#93c5fd",
		"pickerGroup.foreground": "#93c5fd",
		"progressBar.background": "#93c5fd",
		"scrollbar.shadow": "#181926",
		"scrollbarSlider.activeBackground": "#37415166",
		"scrollbarSlider.background": "#5b607880",
		"scrollbarSlider.hoverBackground": "#6e738d",
		"settings.focusedRowBackground": "#5b607833",
		"settings.headerForeground": "#cad3f5",
		"settings.modifiedItemIndicator": "#93c5fd",
		"settings.dropdownBackground": "#494d64",
		"settings.dropdownListBorder": "#00000000",
		"settings.textInputBackground": "#494d64",
		"settings.textInputBorder": "#00000000",
		"settings.numberInputBackground": "#494d64",
		"settings.numberInputBorder": "#00000000",
		"banner.background": "#494d64",
		"banner.foreground": "#cad3f5",
		"banner.iconForeground": "#cad3f5",
		"commandCenter.foreground": "#b8c0e0",
		"commandCenter.inactiveForeground": "#b8c0e0",
		"commandCenter.activeForeground": "#93c5fd",
		"commandCenter.background": "#1e2030",
		"commandCenter.activeBackground": "#5b607833",
		"commandCenter.border": "#00000000",
		"commandCenter.inactiveBorder": "#00000000",
		"commandCenter.activeBorder": "#93c5fd",
		"symbolIcon.textForeground": "#cad3f5",
		"symbolIcon.arrayForeground": "#f5a97f",
		"symbolIcon.booleanForeground": "#93c5fd",
		"symbolIcon.classForeground": "#eed49f",
		"symbolIcon.colorForeground": "#f5bde6",
		"symbolIcon.constantForeground": "#f5a97f",
		"symbolIcon.constructorForeground": "#b7bdf8",
		"symbolIcon.enumeratorForeground": "#eed49f",
		"symbolIcon.enumeratorMemberForeground": "#eed49f",
		"symbolIcon.eventForeground": "#f5bde6",
		"symbolIcon.fieldForeground": "#cad3f5",
		"symbolIcon.fileForeground": "#93c5fd",
		"symbolIcon.folderForeground": "#93c5fd",
		"symbolIcon.functionForeground": "#8aadf4",
		"symbolIcon.interfaceForeground": "#eed49f",
		"symbolIcon.keyForeground": "#8bd5ca",
		"symbolIcon.keywordForeground": "#93c5fd",
		"symbolIcon.methodForeground": "#8aadf4",
		"symbolIcon.moduleForeground": "#cad3f5",
		"symbolIcon.namespaceForeground": "#eed49f",
		"symbolIcon.nullForeground": "#ee99a0",
		"symbolIcon.numberForeground": "#f5a97f",
		"symbolIcon.objectForeground": "#eed49f",
		"symbolIcon.operatorForeground": "#8bd5ca",
		"symbolIcon.packageForeground": "#f0c6c6",
		"symbolIcon.propertyForeground": "#ee99a0",
		"symbolIcon.referenceForeground": "#eed49f",
		"symbolIcon.snippetForeground": "#f0c6c6",
		"symbolIcon.stringForeground": "#a6da95",
		"symbolIcon.structForeground": "#8bd5ca",
		"symbolIcon.typeParameterForeground": "#ee99a0",
		"symbolIcon.unitForeground": "#cad3f5",
		"symbolIcon.variableForeground": "#cad3f5",
		"charts.foreground": "#cad3f5",
		"charts.lines": "#b8c0e0",
		"charts.red": "#ed8796",
		"charts.blue": "#8aadf4",
		"charts.yellow": "#eed49f",
		"charts.orange": "#f5a97f",
		"charts.green": "#a6da95",
		"charts.purple": "#93c5fd",
		"errorLens.errorBackground": "#ed879626",
		"errorLens.errorBackgroundLight": "#ed879626",
		"errorLens.errorForeground": "#ed8796",
		"errorLens.errorForegroundLight": "#ed8796",
		"errorLens.errorMessageBackground": "#ed879626",
		"errorLens.hintBackground": "#a6da9526",
		"errorLens.hintBackgroundLight": "#a6da9526",
		"errorLens.hintForeground": "#a6da95",
		"errorLens.hintForegroundLight": "#a6da95",
		"errorLens.hintMessageBackground": "#a6da9526",
		"errorLens.infoBackground": "#8aadf426",
		"errorLens.infoBackgroundLight": "#8aadf426",
		"errorLens.infoForeground": "#8aadf4",
		"errorLens.infoForegroundLight": "#8aadf4",
		"errorLens.infoMessageBackground": "#8aadf426",
		"errorLens.statusBarErrorForeground": "#ed8796",
		"errorLens.statusBarHintForeground": "#a6da95",
		"errorLens.statusBarIconErrorForeground": "#ed8796",
		"errorLens.statusBarIconWarningForeground": "#f5a97f",
		"errorLens.statusBarInfoForeground": "#8aadf4",
		"errorLens.statusBarWarningForeground": "#f5a97f",
		"errorLens.warningBackground": "#f5a97f26",
		"errorLens.warningBackgroundLight": "#f5a97f26",
		"errorLens.warningForeground": "#f5a97f",
		"errorLens.warningForegroundLight": "#f5a97f",
		"errorLens.warningMessageBackground": "#f5a97f26",
		"editorBracketHighlight.foreground1": "#ed8796",
		"editorBracketHighlight.foreground2": "#f5a97f",
		"editorBracketHighlight.foreground3": "#eed49f",
		"editorBracketHighlight.foreground4": "#a6da95",
		"editorBracketHighlight.foreground5": "#7dc4e4",
		"editorBracketHighlight.foreground6": "#93c5fd",
		"editorBracketHighlight.unexpectedBracket.foreground": "#ee99a0",
		"button.secondaryBorder": "#93c5fd",
		"table.headerBackground": "#363a4f",
		"table.headerForeground": "#cad3f5",
		"list.focusAndSelectionBackground": "#494d64",
	},
};
